In [1]:
from sentence_transformers import SentenceTransformer, util

# Doc's example sentences
sentences = [
    "A man is eating pasta.",
    "Someone is enjoying a bowl of spaghetti.",
    "The stock market dropped today.",
    "A woman plays the violin on stage.",
]

# Exercise: a small "held-out" test set — (sentence A, sentence B, should they be similar?)
pairs = [
    ("How do I reset my password?", "I forgot my login credentials.", True),
    ("The car won't start in the morning.", "My vehicle has engine trouble.", True),
    ("She adopted a puppy last week.", "They got a new dog recently.", True),
    ("How do I reset my password?", "The recipe needs two eggs.", False),
    ("The car won't start in the morning.", "Interest rates rose again.", False),
    ("It is very hot outside.", "It is very cold outside.", False),
]

for name in ["all-MiniLM-L6-v2", "BAAI/bge-small-en-v1.5", "sentence-transformers/all-mpnet-base-v2"]:
    model = SentenceTransformer(name)
    emb = model.encode(sentences, convert_to_tensor=True, normalize_embeddings=True)
    print(f"\n=== {name} ({model.get_sentence_embedding_dimension()} dims) ===")
    print(util.cos_sim(emb, emb).round(decimals=3))

    a = model.encode([p[0] for p in pairs], convert_to_tensor=True, normalize_embeddings=True)
    b = model.encode([p[1] for p in pairs], convert_to_tensor=True, normalize_embeddings=True)
    scores = [round(float(util.cos_sim(a[i], b[i])), 2) for i in range(len(pairs))]
    print("pair scores:", scores)

c:\Users\T0517ZR\ai-trainee\.venv\Lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:11: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm, trange
c:\Users\T0517ZR\ai-trainee\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\T0517ZR\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Pyth


=== all-MiniLM-L6-v2 (384 dims) ===
tensor([[ 1.0000,  0.5850, -0.0400,  0.0220],
        [ 0.5850,  1.0000, -0.0420,  0.1690],
        [-0.0400, -0.0420,  1.0000, -0.0680],
        [ 0.0220,  0.1690, -0.0680,  1.0000]])
pair scores: [0.64, 0.37, 0.56, 0.02, 0.06, 0.76]


c:\Users\T0517ZR\ai-trainee\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\T0517ZR\.cache\huggingface\hub\models--BAAI--bge-small-en-v1.5. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP 


=== BAAI/bge-small-en-v1.5 (384 dims) ===
tensor([[1.0000, 0.7990, 0.3990, 0.3520],
        [0.7990, 1.0000, 0.4540, 0.4740],
        [0.3990, 0.4540, 1.0000, 0.3240],
        [0.3520, 0.4740, 0.3240, 1.0000]])
pair scores: [0.82, 0.74, 0.8, 0.38, 0.39, 0.87]


c:\Users\T0517ZR\ai-trainee\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\T0517ZR\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back


=== sentence-transformers/all-mpnet-base-v2 (768 dims) ===
tensor([[ 1.0000,  0.6480,  0.0310, -0.0780],
        [ 0.6480,  1.0000,  0.0010,  0.0400],
        [ 0.0310,  0.0010,  1.0000,  0.0840],
        [-0.0780,  0.0400,  0.0840,  1.0000]])
pair scores: [0.59, 0.53, 0.69, 0.09, 0.11, 0.48]


In [2]:
from sentence_transformers import SentenceTransformer

my_pairs = [
    ("I got a new laptop.", "I got a new computer.", True),
    ("My phone won't turn on.", "My phone won't charge.", True),
    ("The person is sick.", "The person has a runny nose.", True),
    ("My car won't drive.", "My laptop won't turn on.", False),
    ("The bottle is broken.", "I don't have a charger.", False),
    ("It's going up.", "It's going down.", False),
]

for name in ["all-MiniLM-L6-v2", "BAAI/bge-small-en-v1.5", "sentence-transformers/all-mpnet-base-v2"]:
    model = SentenceTransformer(name)
    a = model.encode([p[0] for p in my_pairs], normalize_embeddings=True)
    b = model.encode([p[1] for p in my_pairs], normalize_embeddings=True)
    scores = (a * b).sum(axis=1)   # dot product = cosine, since normalized
    print(name, [round(float(s), 2) for s in scores])

all-MiniLM-L6-v2 [0.87, 0.76, 0.7, 0.45, -0.0, 0.84]
BAAI/bge-small-en-v1.5 [0.94, 0.86, 0.83, 0.64, 0.48, 0.84]
sentence-transformers/all-mpnet-base-v2 [0.92, 0.72, 0.6, 0.51, 0.02, 0.73]


**all-MiniLM-L6-v2** did best on my test set. It had the biggest gap between similar and unrelated pairs (0.35), compared with 0.33 for all-mpnet-base-v2 and 0.22 for bge-small-en-v1.5.

In [3]:
import numpy as np, faiss, pandas as pd, time
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")
corpus = pd.read_csv("../day02/data/raw/imdb_train.csv")["text"].head(20000).tolist()

emb = model.encode(corpus, batch_size=64, show_progress_bar=True, normalize_embeddings=True)
emb = np.array(emb, dtype="float32")
print(emb.shape)

Batches: 100%|██████████| 313/313 [09:03<00:00,  1.74s/it]

(20000, 384)


In [4]:
index = faiss.IndexFlatIP(emb.shape[1])   # exact search, inner product (= cosine)
index.add(emb)
print("Vectors in index:", index.ntotal)

query = model.encode(["a scary movie that kept me up at night"],
                     normalize_embeddings=True).astype("float32")
t = time.time()
D, I = index.search(query, k=5)
print(f"Search took {(time.time()-t)*1000:.1f} ms")

for rank, (score, idx) in enumerate(zip(D[0], I[0])):
    print(f"{rank+1}. score={score:.3f}  {corpus[idx][:120]}")

Vectors in index: 20000
Search took 10.6 ms
1. score=0.702  The late, great Robert Bloch (author of PSYCHO, for those of you who weren't paying attention) scripted this tale of ter
2. score=0.664  this movie scared me so bad, i am easily scared though so its no big thing but this movie was scary and whoever wasnt sc
3. score=0.649  I went to see this movie expecting a nice relaxing time in the theater with my younger sister. Instead, I had to really 
4. score=0.628  I wish I could give this movie a zero out of ten. Before going to this movie the day after it came out, I came on IMDb t
5. score=0.627  normally i'm not the sort to be scared by horror movies, but this movie is the exception. some how this movie got into m


In [5]:
# Save the index to a file
faiss.write_index(index, "imdb_minilm.faiss")

# Load it back, like you would after a restart
index2 = faiss.read_index("imdb_minilm.faiss")
print("Loaded vectors:", index2.ntotal)

# Check it gives the exact same search results as the original
D2, I2 = index2.search(query, k=5)
print("Same results as before:", (I2 == I).all())

Loaded vectors: 20000
Same results as before: True


In [6]:
import pickle, faiss, time
from sentence_transformers import SentenceTransformer

index = faiss.read_index("wiki.faiss")
corpus = pickle.load(open("corpus.pkl", "rb"))
model = SentenceTransformer("all-MiniLM-L6-v2")

titles = sorted({c.split(":")[0] for c in corpus})
print(len(titles), "articles")
print(titles[:300])

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: b4283c9e-b24f-4729-af82-245d004808dd)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/modules.json
Retrying in 1s [Retry 1/5].
c:\Users\T0517ZR\ai-trainee\.venv\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


3440 articles
['0', '1', '1 (number)', '10', '10 (number)', '1000 (number)', '11', '112 (emergency telephone number)', '1153', '1191', '12', '1227', '1254', '1267', '13', '1324', '1431', '1438', '1452', '1466', '1469', '1473', '1485', '1492', '1502', '1519', '1533', '1536', '1539', '1542', '1546', '1564', '1574', '1598', '1600', '1603', '1621', '1642', '1651', '1659', '1687', '1715', '1723', '1724', '1735', '1740', '1745', '1756', '1774', '1783', '1785', '1787', '1788', '1789', '1796', '1804', '1806', '1809', '1812', '1813', '1815', '1820', '1822', '1824', '1826', '1827', '1833', '1834', '1836', '1838', '1844', '1850', '1857', '1858', '1860s', '1865', '1869', '1870', '1871', '1872', '1874', '1875', '1879', '1882', '1885', '1887', '1888', '1890', '1892', '1894', '1895', '1898', '1899', '1902', '1903', '1904', '1907', '1909', '1911', '1912', '1913', '1914', '1918', '1919', '1920', '1920s', '1921', '1922', '1923', '1924', '1925', '1926', '1927', '1928', '1929', '1930', '1930s', '1931', '1

In [7]:
tests = [
    ("the fourth month of the year",                              "April"),
    ("month named after the Roman emperor Augustus",               "August"),
    ("painting, sculpture and other creative things people make",  "Art"),
    ("the mixture of gases that we breathe",                       "Air"),
    ("British mathematician who broke German codes in World War 2","Alan Turing"),
    ("Canadian singer who made the album Jagged Little Pill",      "Alanis Morissette"),
    ("computer program for drawing vector graphics",               "Adobe Illustrator"),
    ("spicy smoked sausage from France and Louisiana",             "Andouille"),
    ("growing crops and raising animals for food",                 "Farming"),
    ("adding, subtracting, multiplying and dividing numbers",      "Arithmetic"),
]

# Safety check: are all these articles actually in the corpus?
missing = [t for _, t in tests if not any(c.startswith(t + ":") for c in corpus)]
print("Titles not in corpus:", missing)

hits = 0
for query, title in tests:
    qv = model.encode([query], normalize_embeddings=True).astype("float32")
    t = time.perf_counter()
    D, I = index.search(qv, 5)
    ms = (time.perf_counter() - t) * 1000
    hit = any(corpus[i].startswith(title + ":") for i in I[0])
    hits += hit
    print(f"{'HIT ' if hit else 'MISS'}  {ms:5.1f} ms  {query}")

print(f"\nRecall@5 = {hits}/{len(tests)} = {hits/len(tests):.1f}")

Titles not in corpus: []
HIT     3.2 ms  the fourth month of the year
HIT     2.2 ms  month named after the Roman emperor Augustus
HIT     2.0 ms  painting, sculpture and other creative things people make
HIT     1.9 ms  the mixture of gases that we breathe
MISS    2.2 ms  British mathematician who broke German codes in World War 2
HIT     2.2 ms  Canadian singer who made the album Jagged Little Pill
HIT     1.9 ms  computer program for drawing vector graphics
HIT     2.1 ms  spicy smoked sausage from France and Louisiana
HIT     2.5 ms  growing crops and raising animals for food
MISS    2.1 ms  adding, subtracting, multiplying and dividing numbers

Recall@5 = 8/10 = 0.8


In [8]:
for query in ["British mathematician who broke German codes in World War 2",
              "adding, subtracting, multiplying and dividing numbers"]:
    qv = model.encode([query], normalize_embeddings=True).astype("float32")
    D, I = index.search(qv, 5)
    print(f"\nQUERY: {query}")
    for score, i in zip(D[0], I[0]):
        print(f"  {score:.3f}  {corpus[i][:100]}")


QUERY: British mathematician who broke German codes in World War 2
  0.553  December 18: writer (b. 1744) 1829 - Jean-Baptiste Lamarck, French soldier and biologist (b. 1744) 1
  0.548  List of mathematicians: Germany Carl Gustav Jacob Jacobi Great Britain England Charles Babbage, cred
  0.511  December 8: mathematician (b. 1821) 1901 2000 1903 – Herbert Spencer, English philosopher and sociol
  0.510  November 20: Great Britain (b. 1683) 1742 – Melchior de Polignac, French diplomat (b. 1661) 1758 - J
  0.493  April 9: flute. 1802 – Elias Lönnrot, Finnish physician and writer (d. 1884) 1806 – Isambard Kingdom

QUERY: adding, subtracting, multiplying and dividing numbers
  0.603  Algebra: when faced with a problem that is too hard to solve any other way. Problems such as buildin
  0.600  Addition: make a new number, which is the "sum" or total that is expressed with the equals sign. The
  0.593  Subtraction: Non-associativity Subtraction is non-associative, which comes up when one trie